=== bear-metal-apps/libkoala/lib/assets/schemas/data_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Beariscope Data Schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "metadata": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    },
    "auto": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    },
    "tele": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    },
    "endgame": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/dataField"
      }
    }
  },
  "required": [
    "version",
    "metadata",
    "auto",
    "tele",
    "endgame"
  ],
  "$defs": {
    "dataField": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "display_name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "integer",
            "string",
            "boolean",
            "array"
          ]
        },
        "enum": {
          "type": "array",
          "items": { "type": "string" }
        },
        "items": {
          "type": "string",
          "enum": [
            "integer",
            "string",
            "boolean"
          ]
        }
      },
      "required": [
        "id",
        "display_name",
        "type"
      ]
    }
  }
}

=== bear-metal-apps/libkoala/lib/schemas/2025/1_strat.json
{
  "$schema": "/schemas/data_schema.json",
  "version": 1,
  "metadata": [
    {
      "id": "match_number",
      "display_name": "Match Number",
      "type": "integer"
    },
    {
      "id": "event_key",
      "display_name": "Event Key",
      "type": "string"
    },
    {
      "id": "is_red_alliance",
      "display_name": "Red Alliance",
      "type": "boolean"
    },
    {
      "id": "human_net_scored",
      "display_name": "Human Scored",
      "type": "integer"
    },
    {
      "id": "human_net_missed",
      "display_name": "Human Missed",
      "type": "integer"
    },
    {
      "id": "team_strategy",
      "display_name": "Team Strategy",
      "type": "array",
      "items": "integer"
    },
    {
      "id": "driving_skill",
      "display_name": "Driving Skill",
      "type": "array",
      "items": "integer"
    },
    {
      "id": "mechanical_soundness",
      "display_name": "Mechanical Soundness",
      "type": "array",
      "items": "integer"
    }
  ],
  "auto": [
  ],
  "tele": [
  ],
  "endgame": [
  ]
}

=== bear-metal-apps/libkoala/lib/assets/schemas/2025/1_match.json
{
  "$schema": "/assets/schemas/data_schema.json",
  "version": 1,
  "metadata": [
    {
      "id": "match_number",
      "display_name": "Match Number",
      "type": "integer"
    },
    {
      "id": "event_key",
      "display_name": "Event Key",
      "type": "string"
    },
    {
      "id": "is_red_alliance",
      "display_name": "Is Red Alliance",
      "type": "boolean"
    },
    {
      "id": "start_position",
      "display_name": "Start Position",
      "type": "string",
      "enum": [
        "1",
        "2",
        "3"
      ]
    },
    {
      "id": "notes",
      "display_name": "Notes",
      "type": "string"
    }
  ],
  "auto": [
    {
      "id": "stopped",
      "display_name": "Stopped",
      "type": "boolean"
    },
    {
      "id": "collected_algae",
      "display_name": "Collected Algae",
      "type": "integer"
    },
    {
      "id": "reef_removed_algae",
      "display_name": "Removed Algae",
      "type": "integer"
    },
    {
      "id": "processed_algae",
      "display_name": "Processed Algae",
      "type": "integer"
    },
    {
      "id": "collected_coral",
      "display_name": "Collected Coral",
      "type": "integer"
    },
    {
      "id": "reef_level_1_placed",
      "display_name": "L1 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_1_missed",
      "display_name": "L1 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_placed",
      "display_name": "L2 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_missed",
      "display_name": "L2 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_placed",
      "display_name": "L3 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_missed",
      "display_name": "L3 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_placed",
      "display_name": "L4 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_missed",
      "display_name": "L4 Missed",
      "type": "integer"
    },
    {
      "id": "net_scored",
      "display_name": "Net Scored",
      "type": "integer"
    },
    {
      "id": "net_missed",
      "display_name": "Net Missed",
      "type": "integer"
    }
  ],
  "tele": [
    {
      "id": "lost_comms",
      "display_name": "Lost Comms",
      "type": "boolean"
    },
    {
      "id": "played_defense",
      "display_name": "Played Defense",
      "type": "boolean"
    },
    {
      "id": "reef_removed_algae",
      "display_name": "Removed Algae",
      "type": "integer"
    },
    {
      "id": "processed_algae",
      "display_name": "Processed Algae",
      "type": "integer"
    },
    {
      "id": "collected_coral",
      "display_name": "Collected Coral",
      "type": "integer"
    },
    {
      "id": "reef_level_1_placed",
      "display_name": "L1 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_1_missed",
      "display_name": "L1 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_placed",
      "display_name": "L2 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_2_missed",
      "display_name": "L2 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_placed",
      "display_name": "L3 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_3_missed",
      "display_name": "L3 Missed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_placed",
      "display_name": "L4 Placed",
      "type": "integer"
    },
    {
      "id": "reef_level_4_missed",
      "display_name": "L4 Missed",
      "type": "integer"
    },
    {
      "id": "net_scored",
      "display_name": "Net Scored",
      "type": "integer"
    },
    {
      "id": "net_missed",
      "display_name": "Net Missed",
      "type": "integer"
    }
  ],
  "endgame": [
    {
      "id": "cage",
      "display_name": "Cage",
      "type": "string",
      "enum": [
        "park",
        "shallow",
        "deep"
      ]
    }
  ]
}
